### ISSUE TITLE
Problem with compilation of Auto-07p 0.9.2 on Ubuntu 20.04.1 x64

### ISSUE THREAD

**Issue by edgardeitor** [auto-07p/auto-07p#10]
Following the previous manual found in the Web, I put on terminal the following command once inside the auto-07p-0.9.2:

./configure --enable-gui

After this, everything seems fine up until the end, but it appears the following message:

It was requested that the plotting utility PLAUT04 
be compiled but the proper libraries (Coin3D and   
SoQt or SoXt or Open Inventor and Open Inventor Xt)
and perhaps Motif libraries (libXm) could not be   
found. The compilation of PLAUT04 is disabled.

Is there any solution? I have experienced this before and I couldn't plot 3D solutions with plot3 command.

Previously, I ran these commands:

sudo apt-get update
sudo apt-get install gfortran
sudo apt-get install python3-matplotlib 
sudo apt-get install ipython3
sudo apt-get install libsoqt-dev
sudo apt-get install libsimage-dev
sudo apt-get install libmotif-dev
sudo apt-get install transfig
sudo apt-get install libcanberra-gtk*

I am currently using Ubuntu 20.04.1. I didn't have this problem in Ubuntu 18.04.4.

**Comment by mray271** [comment]
Same issue.  I have tried installing coin3d from source  https://github.com/coin3d/coin and get the same error.
Any recommended things to try on Fedora 33 ? 

The output of 
coin-config --libs
is
/usr/local/lib64
and in that directory I have
libCoin.so 
libCoin.so.80.0.1
and

**Comment by edgardeitor** [comment]
I installed the version that has all its files in the Code section, and everything worked fine.

I think that some important files were updated after the release of Auto07p 0.9.2

**Comment by mray271** [comment]
@edgardeitor  which version worked for you? Can you post a link or the commit hash?

**Comment by edgardeitor** [comment]
It does not have a number, I guess. I just downloaded all the files from here: https://github.com/auto-07p/auto-07p and then compiled auto in the usual way

./configure
make

That should work if you previously installed the right packages for python to work.

**Comment by mray271** [comment]
Very interesting. I can confirm the build is working for me too now!  Wondering if there was some bug in an upstream dependency that got fixed.

**Comment by edgardeitor** [comment]
As you can see in the same webpage I posted before, some files were updated 13 months ago (fixing the compatibility with SoQt5 libraries). That was after the release of auto07p 0.9.2 then those changes are not included in the last official version but the nonofficial one

**Comment by mray271** [comment]
Thanks that clears that up. Sounds like the current stable release would benefit from a bug fix release or we can hope developers will tag a new release from master soon.
