### ISSUE TITLE
new minor release (and misc questions)?

### ISSUE THREAD

**Issue by skirpichev** [auto-07p/auto-07p#2]
Hello, I'm current maintainer of the Debian [auto-07p package](https://tracker.debian.org/pkg/auto-07p).  IIUC, this Github repo is the new "official" place for development of the auto-07p?

I see, some (almost all?) Python3 compatibility issues were solved here, as well some problems with newer numpy/matplotlib (https://sourceforge.net/p/auto-07p/support-requests/7/ and so on).  Now about making a new minor release?  Missing Py3 support is an important issue for the next Debian release (see [#936164](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936164)).

**Comment by bartoldeman** [comment]
Correct, it's the new place.

I hope to do a new release in a week or 2, time permitting. The manual needs a bit of work to be updated still.

Yes, I am not aware of any remaining py3 issues, I ran the whole test-suite with py3 without issue a few months ago.

I started working on continuous integration (which does a build on Ubuntu 18.04 and runs all demos), see https://github.com/auto-07p/auto-07p/actions , to which I will also add a demo run using py3.

**Comment by bartoldeman** [comment]
Ah i see that Debian is going to remove the `python` command. Which means a little bit more work needs to be done for the shell scripts auto and autox etc. but that's not hard.

**Comment by skirpichev** [comment]
> Ah i see that Debian is going to remove the python command.

I'm not sure, it seems, symlink will be present, to honor PEP 394.

I don't know if you are planning to support python2 after it will be not maintained anymore (~2 months).  If so, "fixing" shell scripts and sha-bangs to use python3 - may be too much.  It will be not hard to support such patch for the Debian package.

**Comment by skirpichev** [comment]
> Yes, I am not aware of any remaining py3 issues, I ran the whole test-suite with py3 without issue a few months ago.

There is an issue with IPython (https://sourceforge.net/p/auto-07p/bugs/7/) with patch.  It would be great, if that issue will be closed on the next release.

**Comment by bartoldeman** [comment]
The IPython stuff was fixed a while ago (even in the SF SVN), and the github repo has more changes to support IPython > 1.x and then >=5 (e8a7fe03c9a).
I'll update the SF bug tracker later, need to go out now.

**Comment by bartoldeman** [comment]
> I don't know if you are planning to support python2 after it will be not maintained anymore (~2 months).

We'll see. Academic environments can be rather conservative with researchers stuck on CentOS 7 (for which RH is going to need to maintain Python2.7 support for some more years) or even 6 for years, with older software, and no time to manually install newer software. HPC environments work around that using environment modules, but as I work in HPC I'll be quite familiar with the speed by which Python2 will really be dropped.

**Comment by skirpichev** [comment]
> The IPython stuff was fixed a while ago

Indeed, I was trying to work with a wrong Python version on my system (ipython was installed only for Py3).  Sorry to bother you.

**Comment by skirpichev** [comment]
> I hope to do a new release in a week or 2, time permitting.

Just a kind reminder.  Maybe it would be better to package a git-snapshot for the Debian?

**Comment by bartoldeman** [comment]
I was actually very close to a release when you wrote that. It's up now.

**Comment by skirpichev** [comment]
@bartoldeman, thank you.  The Debian's package was updated.  There are few patches:
https://salsa.debian.org/science-team/auto-07p/tree/master/debian/patches

Probably some (mostly coming from solving lintian warnings) worth merging to the upstream (02_env.patch, 04_fix_bashisms.patch).
