### ISSUE TITLE
Black screen in PyPLAUT

### ISSUE THREAD

**Issue by manroygood** [auto-07p/auto-07p#25]
New installation of AUTO on a Mac running 12.3.1. Running the cusp demo, and PyPLAUT gives an almost totally black screen:

<img width="760" alt="Screen Shot 2022-05-13 at 9 41 25 PM" src="https://user-images.githubusercontent.com/31519627/168406208-d9176426-5851-447f-b3a1-fe507e3767ed.png">

I followed the tutorial's instructions for compiling PyPLAUT. I had to do force homebrew to link certain libraries, but in the end it compiled with a lot of warnings.

**Comment by bartoldeman** [comment]
Sorry I missed it but it was resolved using private email.

For posterity: in the end this turned out to be a python issue with HomeBrew: python2 was still used as "default python" but python-tk was installed for python3. Using python3 consistently fixed this issue.
