### ISSUE TITLE
BUG: Detection of user-supplied functions depending on eigenvalues

### ISSUE THREAD

**Issue by znicolaou** [auto-07p/auto-07p#35]
I am studying bifurcations of limit cycles in symmetric systems that exhibit branching at nonsimple singular points (e.g. where two real Floquet multipliers simultaneously pass through +1). 

Neither the BP function nor the SPB function changes signs at such points, so I have been trying to define an overloaded parameter value to locate them. In particular, I use GETP('EIG',IND,U) in my PVALS functions to get the Floquet multipliers, and I set PAR(I) to the third smallest real eigenvalue sorted by distance to 1 in absolute value (since the first is trivially 1 and the second is already well detected by BP and LP functions). I then set UZR={I:1} to try to identify these special points where two real multipliers change stability.

The issue is that when the value of PAR(I) changes sign, AUTO enters the routine LCSPBV to locate the special point, but the Floquet multipliers are not recomputed between the steps in the Mueller iterations. Thus, the value of PAR(I) does not change, and the point is poorly detected. 

I implemented a few changes to src/bvp.f90 (see the diff below) to resolve this for my case, and it works quite well as I can branch switch from those equivariant bifurcations that were previously undetected. However, I'm not sure if this resolves the issue for all problem types or breaks anything else. Also, I'm not sure if such technical details are still being maintained. If there is interest, I'd be happy to provide more information.

```
diff --git a/src/bvp.f90 b/src/bvp.f90
index 3062fab..6c59e24 100644
--- a/src/bvp.f90
+++ b/src/bvp.f90
@@ -280,7 +280,31 @@ CONTAINS
              CALL PVLI(AP,ICP,UPS,NDIM,PAR,FNCI)
              IF(IID.GE.2)WRITE(9,*)
           ENDIF
-          DO ITEST=1,AP%NTEST
+          ! ZGN: Check for bifurcations first, before new call to FNCI on 301
+          DO ITEST=NUZR+1,AP%NTEST
+             ! Check for special points
+             CALL LCSPBV(AP,DSOLD,DSTEST,PAR,ICP,ITEST,FUNI,BCNI,ICNI,FNCI, &
+                  TEST(ITEST),RLCUR,RLOLD,RLDOT,NDIM,UPS,UOLDPS,UDOTPS, &
+                  UPOLDP,TM,DTM,P0,P1,EV,THL,THU,IUZ,VUZ,NITPS,ATYPE,STEPPED, &
+                  NTSTNA)
+             IF(STEPPED)ISTEPPED=ITEST
+             IF(LEN_TRIM(ATYPE)>0)THEN
+                IFOUND=ITEST
+                AP%ITP=LBITP(ATYPE,.TRUE.)
+                AP%ITP=AP%ITP+SIGN(10,AP%ITP)*ITPST
+             ENDIF
+          ENDDO
+
+          ! ZGN: Before checking UZRS, recalculate Floquet
+          IF(IAM==0)THEN
+             AP%IID=0 ! Disable repeated print
+             SP1 = FNCI(AP,ICP,UPS,NDIM,PAR,3,ATYPEDUM) ! New FNCI call
+             AP%IID=IID ! Restore IID
+             CALL PVLI(AP,ICP,UPS,NDIM,PAR,FNCI)
+             IF(IID.GE.2)WRITE(9,*)
+          ENDIF
+          ! ZGN: Now check UZR
+          DO ITEST=1,NUZR
              ! Check for special points
              CALL LCSPBV(AP,DSOLD,DSTEST,PAR,ICP,ITEST,FUNI,BCNI,ICNI,FNCI, &
                   TEST(ITEST),RLCUR,RLOLD,RLDOT,NDIM,UPS,UOLDPS,UDOTPS, &
@@ -1264,7 +1288,7 @@ CONTAINS
 
     INTEGER I,IAM,IID,ITMX,IBR,NTOT,NTOP,NITSP1,ISTOP,NCOL,NFPR,NITPSS
     LOGICAL SEARCH
-    DOUBLE PRECISION DS,DSMAX,EPSS,Q0,Q1,DQ,RDS,RRDS,S0,S1
+    DOUBLE PRECISION DS,DSMAX,EPSS,Q0,Q1,DQ,RDS,RRDS,S0,S1,SP1
     DOUBLE PRECISION DETS,FLDFS,DSOLDS,DSTESTS
     CHARACTER(4) :: ATYPEDUM
 
@@ -1399,7 +1423,8 @@ CONTAINS
        ENDIF
 
 ! Check for zero.
-
+       !ZGN: Recalculate FLOWKM before PVLI
+       SP1 = FNCI(AP,ICP,UPS,NDIM,PAR,3,ATYPEDUM) ! New FNCI call
        CALL PVLI(AP,ICP,UPS,NDIM,PAR,FNCI)
        IF(IID.GE.2)WRITE(9,*)
        Q=FNCS(AP,ICP,UPS,PAR,ATYPE,IUZ,VUZ,ITEST,FNCI)
```

**Comment by bartoldeman** [comment]
Hi @znicolaou ,

thanks to the contribution and sorry for the delay (AUTO is more of a personal development project for me these days).
After re-familiarizing with said code (it's been around 13 years), I'm not sure if we need to flip the order of calling test functions between built-in and UZR, though it only makes for some minor changes in output in the test suite (pp3 demo).

I think it may be simpler to put that logic in the toolboxes and always compute Floquet multipliers before calling PVLS, via PVLI, which calls FNCI:
```
diff --git a/src/periodic.f90 b/src/periodic.f90
index 49d3957..ded990c 100644
--- a/src/periodic.f90
+++ b/src/periodic.f90
@@ -1798,10 +1798,20 @@ CONTAINS
     INTEGER, INTENT(IN) :: ITEST
     CHARACTER(LEN=*), INTENT(OUT) :: ATYPE
 
-    Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
-    IF(ITEST==3)THEN
-        Q=FNSPBV(AP,PAR,ATYPE,P0,P1,EV)
-    ENDIF
+    INTEGER NINS
+
+    SELECT CASE(ITEST)
+    CASE(0)
+       ! compute Floquet multipliers before calling PVLS
+       NINS=AP%NINS
+       Q=FNSPBV(AP,PAR,ATYPE,P0,P1,EV)
+       Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
+       AP%NINS=NINS
+    CASE(1:2)
+       Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
+    CASE(3)
+       Q=FNSPBV(AP,PAR,ATYPE,P0,P1,EV)
+    END SELECT
   END FUNCTION FNCSPS
 
 ! ------ --------- -------- ------
```

it needs some special handling for NINS (number of stable eigenvalues/FMs) because test functions take its state into account a little awkwardly. This change cause zero differences in the test suite.

Can you test the above alternative patch?

Then some follow-up bug fixes and clean ups are possible:
1. do the same thing for equilibrium points and maps (done that already locally, left out for brevity)
2. remove the now redundant explicit SP1 = FNCI() call from bvp.f90 (and similarly ae.f90).

**Comment by znicolaou** [comment]
Thanks for looking into it, @bartoldeman ! I'll try it out on my problems this week and let you know how it goes!

**Comment by znicolaou** [comment]
Hi @bartoldeman , I think your patch is almost working with my files, but I had to include one more small change to run it. During the initialization calls of `AUTOI`, the `FNCSPS` apparently can get called before the allocation of the vector `EV`, which (I think) was causing some runtime errors. So I added a check to only compute the multipliers if it is not the zeroth step, i.e. NTOT!=0. Maybe instead the ITEST should be 3 for those initialization calls?
```
diff --git a/src/periodic.f90 b/src/periodic.f90
index 49d3957..75d0c10 100644
--- a/src/periodic.f90
+++ b/src/periodic.f90
     NODIR=0
@@ -1798,10 +1798,22 @@ CONTAINS
     INTEGER, INTENT(IN) :: ITEST
     CHARACTER(LEN=*), INTENT(OUT) :: ATYPE
 
-    Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
-    IF(ITEST==3)THEN
+    INTEGER NINS
+
+    SELECT CASE(ITEST)
+    CASE(0)
+       ! compute Floquet multipliers before calling PVLS
+       NINS=AP%NINS
+       IF(AP%NTOT.NE.0)THEN
         Q=FNSPBV(AP,PAR,ATYPE,P0,P1,EV)
-    ENDIF
+       ENDIF
+       Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
+       AP%NINS=NINS
+    CASE(1:2)
+       Q=FNCSBV(AP,ICP,UPS,NDIM,PAR,ITEST,ATYPE)
+    CASE(3)
+       Q=FNSPBV(AP,PAR,ATYPE,P0,P1,EV)
+    END SELECT
   END FUNCTION FNCSPS
```

**Comment by bartoldeman** [comment]
Hi @znicolaou ,

thanks for the feedback. Indeed PVLS is sometimes called too early when the Floquet multipliers aren't available yet.

What happens is that if both the solution and direction vector are known, AUTO has no need to involve the linear solver and hence doesn't obtain the monodromy matrix (`P1^-1 P0`) at step 0.

Sometimes however, it does obtain that matrix earlier, when the direction vector is *not* known (it'll then solve with the null vector to obtain it), so testing for `NTOT==0` isn't 100% reliable.

So I've used a different test, `IF(ALLOCATED(P0))` and only allocate P0 and P1 once they are needed.
On top of that I split `FNSPBV` into `PVSPBV` and `FNSPBV` to avoid double work, as `PVLS` is already always called directly before `FNSPBV` anyway, and this allows the elimination of the special `FNCI` call in `bvp.f90` for the case when the direction vector has been computed.

This I then filed as PR #40 so I get the benefit of CI, can you double check that works for you?

**Comment by znicolaou** [comment]
That all makes sense, thanks for the detailed explanation @bartoldeman! I will try out the PR in the next day or two.

**Comment by bartoldeman** [comment]
I've merged the PR since it passed all the demos, any feedback is always welcome!

**Comment by znicolaou** [comment]
Thanks, @bartoldeman ! Sorry I've been slow responding--the academic job search has been a little consuming for me this winter...It looks like your solution is great, and I'll likely revisit some continuations soon. I'll let you know if I find any issues!
