### ISSUE TITLE
ld: library not found for -lSystem

### ISSUE THREAD

**Issue by ShurimasKitten** [auto-07p/auto-07p#38]
gfortran  -O -c first_run_k1.f90 -o first_run_k1.o
gfortran  -O first_run_k1.o -o first_run_k1.exe /Users/johnbailie/auto/07p/lib/*.o
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
AUTO Runtime Error: Error running AUTO

~~

-lSystem Error. No idea how to fix, have already tried reconfiguring AUTO. 

Am using a MacBook M1 chip.

**Comment by bartoldeman** [comment]
This isn't really a problem with AUTO but with gfortran on a Mac, it's likely also failing to compile a simple hello world Fortran program.

Please try to make sure XCode is installed correctly and
```
brew update
brew reinstall gfortran
```
(if gfortran was installed using HomeBrew in the first place).
