### ISSUE TITLE
Fixing build failure with Inventor and SoXt

### ISSUE THREAD

**Issue by balbirthomas** [auto-07p/auto-07p#4]
Dear Sir,

Attached are two patches that fix build failure of auto-07p (plaut04) when compiled with Inventor and SoXt. The [fix-failure-to-set-soxtlib.txt](https://github.com/auto-07p/auto-07p/files/4027612/fix-failure-to-set-soxtlib.txt) patch fixes failure to set `SOXTLIB` even when all required libraries are detected and configure options are set to use them. As a result `gmainqt.c++` is always compiled even when SoQt is not used leading to failure. The [inventer-vec3f-header-change.txt](https://github.com/auto-07p/auto-07p/files/4027613/inventer-vec3f-header-change.txt) patch updates headers for current stable Inventor version (2.1.5). 

There were build failures with Coin3D and SoQt also but the changes required were quite extensive, resulting from incompatibilities with Qt5 and current Coin3D versions. The platform on which these builds were done is the current stable Debian GNU/Linux release.

I presume pyplaut is the future and plauto04 is deprecated. In any case this was not too much effort, if it helps.

regards

**Comment by bartoldeman** [comment]
Thanks for the fixes! plaut04 has not been deprecated, but I haven't tested the soxt/coin version in many years, and using the SGI Open Inventor Xt Library I can't even remember, instead using Coin and SoQt with Qt4.

Now I realize that Qt4 is getting old but as you say it's more work to port to Qt5 (it would be most welcome but haven't had time to do that yet). As e.g Ubuntu 18.04 LTS, Debian 10, and Fedora still ship Qt4 and Coin with libsoqt for Qt4 it still works in many cases but not for much longer I see, and Inventor is a nice stopgap alternative with libmotif freely available.

**Comment by bartoldeman** [comment]
I just pushed a change to the configure script to detect Qt5 and try to use SoQt with it. I've only tested this with Debian's libsoqt520-dev package so far. Perhaps this works for you as well?

I was surprised no source code changes were necessary though there do seem to be some runtime warnings. The SoQt version certainly looks prettier.
