### ISSUE TITLE
problem to use AUTO-07p with macOS Catalina 

### ISSUE THREAD

**Issue by Amaa486** [auto-07p/auto-07p#9]
My MacBook is macOS Catalina, Version 10.15.5.
I have installed AUTO-07p, followed the steps as in the manual. BUT there is a problem as explained below. For example when I work on "ab", which is in demos, I typed: 
**>> load(e='ab')** 
# this is no problem for this , but when I typed
**>> rn(c='ab')**
# I have received the following message: 
gfortran -fopenmp -O -c ab.f90 -o ab.o
gfortran -fopenmp -O ab.o -o ab.exe /Users/aldurayhim/Downloads/auto/07p/lib/*.o
Undefined symbols for architecture x86_64:
  "__gfortran_os_error_at", referenced from:
      ___toolboxae_MOD_rnullvc in toolboxae.o
      ___toolboxae_MOD_fnlpae in toolboxae.o
      ___toolboxae_MOD_fncpae in toolboxae.o
      ___toolboxae_MOD_stpnae in toolboxae.o
      ___toolboxae_MOD_fnbtae in toolboxae.o
      ___toolboxae_MOD_stpnbpf in toolboxae.o
      ___toolboxae_MOD_fnbpf in toolboxae.o
      ...
  "dgees", referenced from:
      ___homcont_MOD_prjctn in homcont.o
  "dgeev", referenced from:
      ___homcont_MOD_eigho in homcont.o
      rg in support.o
  "dgemm", referenced from:
      ___homcont_MOD_prjctn in homcont.o
      ___equilibrium_MOD_ffhbx in equilibrium.o
  "dgemv", referenced from:
      ___equilibrium_MOD_fngheq in equilibrium.o
      ___equilibrium_MOD_ffhb in equilibrium.o
  "dtrsen", referenced from:
      ___homcont_MOD_prjctn in homcont.o
  "idamax", referenced from:
      ___solvebv_MOD_conpar in solvebv.o
      _redelim.3 in solvebv.o
      _reducer.6 in solvebv.o
      ___solvebv_MOD_solvbv._omp_fn.0 in solvebv.o
      ___homcont_MOD_eigho in homcont.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Any help please** thanks in advance

**Comment by bartoldeman** [comment]
Can you do:
`ls -l /Users/aldurayhim/Downloads/auto/07p/lib/*.o`
dgemv is normally found in blas.o, it could be that that file's compilation is not up to date.

**Comment by Amaa486** [comment]
Thanks bartoldeman for your reply. I cannot find blas.o in the list, after entering that command I have received:
aldurayhim@MacBook-Pro-alkhas-b-Abdullah ~ % ls -l /Users/aldurayhim/Downloads/auto/07p/lib/*.o
-rw-r--r--  1 aldurayhim  staff  33040 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/ae.o
-rw-r--r--  1 aldurayhim  staff   5136 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/auto_constants.o
-rw-r--r--  1 aldurayhim  staff  62512 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/bvp.o
-rw-r--r--  1 aldurayhim  staff   1264 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/compat.o
-rw-r--r--  1 aldurayhim  staff  46856 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/equilibrium.o
-rw-r--r--  1 aldurayhim  staff  75840 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/homcont.o
-rw-r--r--  1 aldurayhim  staff   8292 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/interfaces.o
-rw-r--r--  1 aldurayhim  staff  86024 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/io.o
-rw-r--r--  1 aldurayhim  staff  19144 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/mesh.o
-rw-r--r--  1 aldurayhim  staff   2424 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/mpi.o
-rw-r--r--  1 aldurayhim  staff  64508 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/solvebv.o
-rw-r--r--  1 aldurayhim  staff  35668 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/support.o
-rw-r--r--  1 aldurayhim  staff  26820 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/toolboxae.o
-rw-r--r--  1 aldurayhim  staff  47720 Jul  9 02:47 /Users/aldurayhim/Downloads/auto/07p/lib/toolboxbv.o
 
As I cann't find the _blas.o_, I thought I should install _blas_ library so I type:
> brew install openblas
but the problem still there.

**Comment by Amaa486** [comment]
Thanks again. The message of error shrank to be:
gfortran -fopenmp -O ab.o -o ab.exe /Users/aldurayhim/Downloads/auto/07p/lib/*.o
Undefined symbols for architecture x86_64:
  "__gfortran_os_error_at", referenced from:
      ___toolboxae_MOD_rnullvc in toolboxae.o
      ___toolboxae_MOD_fnlpae in toolboxae.o
      ___toolboxae_MOD_fncpae in toolboxae.o
      ___toolboxae_MOD_stpnae in toolboxae.o
      ___toolboxae_MOD_fnbtae in toolboxae.o
      ___toolboxae_MOD_stpnbpf in toolboxae.o
      ___toolboxae_MOD_fnbpf in toolboxae.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
AUTO Runtime Error: Error running AUTO

I have followed your instruction in #8 and do the required change in line 257 in maps.f90.
Moreover, for >> fortran -v 
I have received 
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin18/8.2.0/lto-wrapper
Target: x86_64-apple-darwin18
Configured with: ../gcc-8.2.0/configure --prefix=/usr/local/gfortran --with-gmp=/Users/fx/devel/gcc/build_package/deps --enable-languages=c,c++,fortran,objc,obj-c++ --build=x86_64-apple-darwin18 --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 8.2.0 (GCC)

**Comment by bartoldeman** [comment]
Judging from the file stamps I suspect you may have compiled some files in July with a different Fortran compiler than you are using now. Please do
```
cd /Users/aldurayhim/Downloads/auto/07p
make superclean
```
and then recompile everything.

**Comment by Amaa486** [comment]
It is working now. Thanks bartoldeman for your great support.
